version: "3.7"
services:
        bot-sql-server:
                build: ./bot-sql-server
                ports:
                        - "3306:3306"
                volumes:
                        - ./bot-sql-server/data_volume:/var/lib/mysql
        
                