version: "3.3"
services:
        bot-sql-server:
                build: ./bot-sql-server
               

                volumes:
                        - ./bot-sql-server/data_volume:/var/lib/mysql
        tg-bot:
                build: ./bot
                restart: on-failure



                
                
